const GET_FOOD = 'GET_FOOD';
const GET_COPY_FOOD = 'GET_COPY_FOOD';
const GET_DIETS = 'GET_DIETS';
const GET_ID_FOOD = 'GET_ID_FOOD';
const CLEAR_DETAIL = 'CLEAR_DETAIL';
const GET_SEARCH_FOOD = 'GET_SEARCH_FOOD';
const ADD_FOOD = 'ADD_FOOD';
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const ORDER_BY_HSCORE = 'ORDER_BY_HSCORE';
const FILTER_DIETS = 'FILTER_DIETS';
const FILTER_ORIGIN = 'FILTER_ORIGIN';
const SHOW_LOADING = 'SHOW_LOADING';
const ERROR = 'ERROR'

module.exports = {
    GET_FOOD,
    GET_COPY_FOOD,
    GET_DIETS,
    GET_ID_FOOD,
    CLEAR_DETAIL,
    GET_SEARCH_FOOD,
    ADD_FOOD,
    ORDER_BY_NAME,
    ORDER_BY_HSCORE,
    FILTER_DIETS,
    FILTER_ORIGIN,
    SHOW_LOADING,
    ERROR
}
